version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: zxcvb
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"