"""firt_user

Revision ID: 2aaa7aef311b
Revises: bca090464624
Create Date: 2025-06-01 18:05:30.733939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aaa7aef311b'
down_revision: Union[str, None] = 'bca090464624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('short_url', sa.String(length=10), nullable=True))
    op.drop_constraint(op.f('urls_short_code_key'), 'urls', type_='unique')
    op.create_unique_constraint(None, 'urls', ['short_url'])
    op.drop_column('urls', 'short_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('short_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'urls', type_='unique')
    op.create_unique_constraint(op.f('urls_short_code_key'), 'urls', ['short_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('urls', 'short_url')
    # ### end Alembic commands ###
