"""add_table_with_clicks

Revision ID: 44bb6fb9cda5
Revises: ca3fdfc8c140
Create Date: 2025-06-03 15:49:46.985622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44bb6fb9cda5'
down_revision: Union[str, None] = 'ca3fdfc8c140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_clicks_clicked_at'), 'url_clicks', ['clicked_at'], unique=False)
    op.create_index(op.f('ix_url_clicks_id'), 'url_clicks', ['id'], unique=False)
    op.drop_column('urls', 'click_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('click_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_url_clicks_id'), table_name='url_clicks')
    op.drop_index(op.f('ix_url_clicks_clicked_at'), table_name='url_clicks')
    op.drop_table('url_clicks')
    # ### end Alembic commands ###
