"""changed_name_column

Revision ID: ca3fdfc8c140
Revises: ce4ecc38db9f
Create Date: 2025-06-02 17:00:46.376439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca3fdfc8c140'
down_revision: Union[str, None] = 'ce4ecc38db9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('origin_url', sa.String(length=100), nullable=True))
    op.drop_column('urls', 'original_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('original_url', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('urls', 'origin_url')
    # ### end Alembic commands ###
